### ISSUE TITLE
Manifest merger failed with multiple errors, see logs

### ISSUE THREAD

**Issue by Aniskonig** [michaldrabik/TapBarMenu#18]
when i try to run the app it's giving me this error this is [my APP](https://github.com/Aniskonig/myTapbar)
"Manifest merger failed with multiple errors, see logs"

**Comment by michaldrabik** [comment]
Hi,
try invalidating caches and restart AS. Any chances of seeing those errors and logs?
Can you try using version 1.0.5 and see if that happens?

**Comment by Aniskonig** [comment]
ERROR: Failed to resolve: com.github.michaldrabik:TapBarMenu:1.0.5

**Comment by michaldrabik** [comment]
Please use `'com.github.michaldrabik:tapbarmenu:1.0.5'`

**Comment by Aniskonig** [comment]
it's has been solved thank you

**Comment by michaldrabik** [comment]
Good, was it solved for version 1.0.6 or you reverted to 1.0.5?
