### ISSUE TITLE
ERROR: Failed to resolve: com.github.michaldrabik:TapBarMenu:1.0.6

### ISSUE THREAD

**Issue by adnanamin69** [michaldrabik/TapBarMenu#20]

**Comment by adnanamin69** [comment]
whats wrong with my dependecies 
ERROR: Failed to resolve: com.github.michaldrabik:TapBarMenu:1.0.6

**Comment by michaldrabik** [comment]
Did you remember to add Jitpack repo in your top build.gradle file?

**Comment by adnanamin69** [comment]
thanks its start working

**Comment by adnanamin69** [comment]
if you have more menus like this attractive then give me github link please

**Comment by michaldrabik** [comment]
That's the only one for now, sorry :)

**Comment by adnanamin69** [comment]
ok thanks for your response
