### ISSUE TITLE
Can I make this menu vertical when screen is in landscape mode?

### ISSUE THREAD

**Issue by ghost** [michaldrabik/TapBarMenu#21]
If not, would be cool if you give directions how to extend it and what to change, so it can be made vertical. Thanks

**Comment by michaldrabik** [comment]
I would need to add two modes let's say MENU_ANCHOR_RIGHT and MENU_ANCHOR_LEFT and based on that all the math that is being used would need to be altered to a new anchor point.

Does not seem to complicated. I might look into it myself but can't promise it's going to be right now.

**Comment by ghost** [comment]
Got you. Thanks for respond. Hope you will add it in the future, cause it's kinda fundamental customization. Also, TabBarMenu is really fast and reliable. I am using it for 3 weeks now and don't see any weak points :)

**Comment by ghost** [comment]
Oops, closed by missclick. Opened again!
