### ISSUE TITLE
Increasing memory usage

### ISSUE THREAD

**Issue by treere** [michaldrabik/TapBarMenu#6]
Repeat open - close several times increases the memory usage

**Comment by JosephTurner** [comment]
Does the memory usage drop after garbage collection?

**Comment by michaldrabik** [comment]
@treere @JosephTurner Yes there are tiny memory allocations made by ValueAnimators when setting float values during opening/closing menu. Memory is being released after GC so I guess it's not a problem.

**Comment by treere** [comment]
@michaldrabik Each open - close increase the memory of 20K on my phone, it's a lot. I'm trying to understand why. 
It's not a big problem because no one ( maybe ) pass his time opening and closing the menu.
@JosephTurner after GC the memory usage drop always at the same amount.

**Comment by treere** [comment]
I think we can close this
