### ISSUE TITLE
Animation delay

### ISSUE THREAD

**Issue by DerEisKoenig** [michaldrabik/TapBarMenu#8]
Just tried to modify a sample project, changing animationDuration resource field (res->values->ints.xml) to any other value - animation is always FAST, without any delay. Checked few times (500,5000,50000)  - without any success. Finally, used some hardcoded value - instead of configuration - works fine only in GenyMotion emulator. Can't get a delay with animation on my phone... Any ideas, how to resolve it?

**Comment by michaldrabik** [comment]
@DerEisKoenig Have you swapped
 `compile 'com.github.michaldrabik:tapbarmenu:1.0.4'` 
with 
`compile project(':library')` 
in sample's project `build.gradle` ?

**Comment by DerEisKoenig** [comment]
No, but my "build.gradle" already has this new line... "compile project(':library')"

**Comment by michaldrabik** [comment]
@DerEisKoenig 
Not sure what might be wrong then. When I change animationDuration resources the duration is changed properly both on my phone and genymotion emulator.

**Comment by DerEisKoenig** [comment]
Looks, like my Meizu is breaking any delays... Strange situation... Will try tomorrow to test with another phones...

**Comment by DerEisKoenig** [comment]
Yes, something is going wrong on Meizu (MX4 Pro). Tried to run the same app on old HTC Desire - it works... For a moment I have no idea, how to fix animation :-(

**Comment by treere** [comment]
Which Api/Rom do you use on your MX4 Pro?
